---
title: "Residence Time Synthesis"
author: "Emmi Mueller"
date: "7/8/2020"
output: pdf_document
---

```{r}
rm(list=ls())

package.list <- c('plyr', 'grid', 'png', 'ggplot2', 'tidyverse', 'here', 'ggpmisc', 'Hmisc', 'ggsignif', 'ggpubr') 
for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) { 
    install.packages(package)
    library(package, character.only=T)
  } }

here()
```

```{r figure_setup}
my.cols <- RColorBrewer::brewer.pal(n = 4, name = "Greys")[3:4]

# Set theme for figures in the paper
theme_set(theme_classic() + 
  theme(axis.title = element_text(size = 15),
        axis.title.x = element_text(margin = margin(t = 15, b = 15)),
        axis.title.y = element_text(margin = margin(l = 15, r = 15)),
        axis.text = element_text(size = 15),
        axis.text.x = element_text(margin = margin(t = 5)),
        axis.text.y = element_text(margin = margin(r = 5)),
        axis.line.x = element_blank(),
        axis.line.y = element_blank(),
        axis.ticks.x = element_line(size = 1),
        axis.ticks.y = element_line(size = 1),
        axis.ticks.length = unit(.1, "in"),
        panel.border = element_rect(color = "black", fill = NA, size = 1.5),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 15),
        strip.text = element_text(size = 20),
        strip.background = element_blank()
        ))
```

#Lake Data

#Questions for Jay:
#-Why only 127 listings? Removing outliers? Does that change for RT and TO?
#-Is all this data from Wikipedia?
```{r}
lakes <-read.csv(here("Powell", "data","Lake_Turnover_20130515.csv"),header=TRUE,sep=",")
head(lakes)
str(lakes)

lakes$logTurnover<-log10(lakes$Turnover)
lakes$logResidence<-log10(lakes$Residence)

Lake_TO <- ggplot(data = lakes, mapping = aes (x = Turnover))+
  geom_histogram(binwidth = 0.5, boundary = 0, fill = "white", color = "black")+
  ylab("Frequency")+
  xlab("Turnover (1/yrs)")
Lake_TO

ggsave("../output/Lake_TO.pdf", width = 15, height = 10)
ggsave("../output/Lake_TO.png", width = 15, height = 10)

Lake_RT <- ggplot(data = lakes, mapping = aes (x = Residence))+
  geom_histogram(binwidth = 0.5, boundary = 0, fill = "white", color = "black")+
  ylab("Frequency")+
  xlab("Residence Time (yrs)")
Lake_RT

ggsave("../output/Lake_TO.pdf", width = 15, height = 10)
ggsave("../output/Lake_TO.png", width = 15, height = 10)

Lake_logTO <- ggplot(data = lakes, mapping = aes (x = logTurnover))+
  geom_histogram(binwidth = 0.5, boundary = 0, fill = "white", color = "black")+
  ylab("Frequency")+
  xlab("Turnover (1/yrs)")
Lake_logTO

ggsave("../output/Lake_logTO.pdf", width = 15, height = 10)
ggsave("../output/Lake_logTO.png", width = 15, height = 10)

Lake_logRT <- ggplot(data = lakes, mapping = aes (x = logResidence))+
  geom_histogram(xlim = c(-3.5, 1.5), binwidth = 0.5, boundary = 0, fill = "white", color = "black")+
  ylab("Frequency")+
  xlab("log(Residence Time (yrs))")
Lake_logRT

ggsave("../output/Lake_logRT.pdf", width = 15, height = 10)
ggsave("../output/Lake_logRT.png", width = 15, height = 10)

```

```{r}
ecosystems <- read.csv(here("Powell","data","20140527_ResidenceTime_Ecosystems_Terrestrial.csv"), header = TRUE, sep = ",")
oind<-order(as.numeric(by(ecosystems$Residence_Time_d,ecosystems$Ecosystem,median,na.rm=T)))
#ecosystems$Ecosystem<-ordered(ecosystems$Ecosystem,levels=levels(ecosystems$Ecosystem)[oind])

#plot(log(ecosystems$Residence_Time_d, 10) ~ ecosystems$Ecosystem)

RT <- ggplot(data = ecosystems, mapping = aes (x = Ecosystem, y= log(Residence_Time_d, 10)))+
  geom_boxplot()+
  xlab("Ecosystem type")+
  ylab("Residence Time (log(days))")+
  theme(axis.text = element_text(size = 12))

ggsave("../output/Ecosystem_turnover.pdf", width = 15, height = 10)
ggsave("../output/Ecosystem_turnover.png", width = 15, height = 10)

RT_jitter <- ggplot(data = ecosystems, mapping = aes(x = Ecosystem, y = log(Residence_Time_d, 10)))+
  geom_violin()+
  geom_point()+
  xlab("Ecosystem type")+
  ylab("Residence Time (log(days))")+
  theme(axis.text = element_text(size = 12))

RT_jitter

ggsave("../output/Ecosystem_RT.pdf", width = 15, height = 10)
ggsave("../output/Ecosystem_RT.png", width = 15, height = 10)

RT_Eco <- ggplot(data = ecosystems, mapping = aes(x = Ecosystem))+
  geom_bar()+
  theme(axis.text = element_text(size = 12))

RT_Eco

ggsave("../output/Ecosystem_counts.pdf", width = 15, height = 10)
ggsave("../output/Ecosystem_counts.png", width = 15, height = 10)

RT_Matrix <- ggplot(data = ecosystems, mapping = aes(x = Matrix, fill = Ecosystem))+
  geom_bar()+
  theme(axis.text = element_text(size = 12))

RT_Matrix

ggsave("../output/Matrix_counts.pdf", width = 15, height = 10)
ggsave("../output/Matrix_counts.png", width = 15, height = 10)


RT_year <- ggplot(data = ecosystems, mapping = aes(x = Year, fill = Ecosystem))+
  geom_histogram()+
  theme(axis.text = element_text(size = 12))

RT_year

ggsave("../output/Year_counts.pdf", width = 15, height = 10)
ggsave("../output/Year_counts.png", width = 15, height = 10)

pairs(ecosystems)
```

#Bonus code
```{r}

boxplot(log(Turnover_Time)~Ecosystem,lakes=Turnover, yaxt="n", xlab ="Ecosystem", ylab = "Biomass Turnover Time (d)")
aty <- axTicks(2)
labels <- sapply(aty,function(i)
            as.expression(bquote(10^ .(i)))
          )
axis(2,at=aty,labels=labels)
```